name: 'Merge JSON to Env'
description: 'Merge JSON strings and convert to environment variables'
inputs:
  jsons:
    description: 'JSON strings to merge (array)'
    required: true
outputs:
  env: # id of output
    description: 'ENV string'
runs:
  using: 'docker'
  image: 'Dockerfile'
